### ISSUE TITLE
non-zero exit codes on syntax error and newlines

### ISSUE THREAD

**Issue by adrelanos** [Samer-Al-iraqi/Non-Regex-Text-Search-and-Replace-for-Linux#3]
How to reproduce:

    str_replace.pl a

----

Actual result:

> Usage: str_replace Search Replace File
> Or: STDIN str_replace Search Replace$

No new line at the end. (The `$` is my shell prompt.) Exit code is `0`.

----

Expected result:

> Usage: str_replace Search Replace File
> Or: STDIN str_replace Search Replace

Non-zero exit code such as `1`.

**Comment by Samer-Al-iraqi** [comment]
fixed!
